# Configuração para salvar os dados em um arquivo físico no seu Linux
spring.datasource.url=jdbc:h2:file:./data/salvouDB
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ativa o console para você testar o SQL se precisar
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 'update' garante que ele não apague os dados ao iniciar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.web.locale=pt-BR
spring.h2.console.settings.web-allow-others=false